version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    # Too much noise with patch releases...
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
